// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtzGFNG_qTjMxQXsaiQ_IWEz1fSB_nzC0',
    appId: '1:239697565672:web:68b2d1e0cc81bd007db65d',
    messagingSenderId: '239697565672',
    projectId: 'recipe-app-f1a3d',
    authDomain: 'recipe-app-f1a3d.firebaseapp.com',
    storageBucket: 'recipe-app-f1a3d.appspot.com',
    measurementId: 'G-7CVDBN6VWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb9-MJDXBA9Hew35KaLWGVdemeAw_IyQQ',
    appId: '1:239697565672:android:8804fe1d052727877db65d',
    messagingSenderId: '239697565672',
    projectId: 'recipe-app-f1a3d',
    storageBucket: 'recipe-app-f1a3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8rNZJIM3rUWGIeUEYkwhxwHtO8Iw-O8',
    appId: '1:239697565672:ios:ed11915b95e5b8f77db65d',
    messagingSenderId: '239697565672',
    projectId: 'recipe-app-f1a3d',
    storageBucket: 'recipe-app-f1a3d.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu8rNZJIM3rUWGIeUEYkwhxwHtO8Iw-O8',
    appId: '1:239697565672:ios:2b28d601e54bc34a7db65d',
    messagingSenderId: '239697565672',
    projectId: 'recipe-app-f1a3d',
    storageBucket: 'recipe-app-f1a3d.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
